### ISSUE TITLE
Not able to clone repo

### ISSUE THREAD

**Issue by vibodhbhosure** [Raghavarya2002/DSA#290]
![image](https://user-images.githubusercontent.com/52785828/194767159-25378a1a-5936-4950-9617-d971a434ad5e.png)

**Comment by Raghavarya2002** [comment]
> ![image](https://user-images.githubusercontent.com/52785828/194767159-25378a1a-5936-4950-9617-d971a434ad5e.png)

first you have to clone my repo , not in yours , and cloning is only one time task not again and again.
and second mistake is that you have wrote .git after dsa in first command that is invalid.
and third one is invalid path as mention in error line , there is no breadth first ...... file , I think.

I'll suggest first learn git & github properly, I'm not demotivating you but I want to teach you that this is not a large  codebase in which something wrong will happen in future because this is personal repo and it does not effect at all to anyone.
when you work at some large codebase if you do something like that, then various wrong things will happen.

I'm attaching some resources here to learn git and github properly. Hope it'll helps.

https://www.youtube.com/playlist?list=PLBGx66SQNZ8aPsFDwb79JrS2KQBTIZo10

videos no. 11-16

**Comment by vibodhbhosure** [comment]
I have forked your repo and cloning that, because that is how I was previously doing it, .git comes as an extension to that link, I haven't added anything extra. Cloning for other repo's worked completely fined. This is is not my first contribution, I have worked previously, I might not be an expert, but I know enough to clone and contribute. The breadth first file is present pls check Hactoberfest2022 > Breadth-First Search...
![image](https://user-images.githubusercontent.com/52785828/194771648-493049bc-859e-4775-ace0-517a76736a8c.png)
